# Generated by Django 4.1.4 on 2022-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(default='defaults/eventimage.jpeg', upload_to='events'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url',
            field=models.ImageField(default='defaults/venueimage.jpeg', upload_to='venues'),
        ),
    ]
