# Generated by Django 4.1.4 on 2022-12-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_alter_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(upload_to='venue/eventimages'),
        ),
    ]
