# Generated by Django 4.1.4 on 2022-12-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='soldOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(upload_to='events'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url',
            field=models.ImageField(upload_to='venues'),
        ),
    ]
